steps:
# Install dependencies and prune dev dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['ci']

# Install React app dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['ci']
  dir: 'the-turkish-shop'

# Install API dependencies if they exist
- name: 'gcr.io/cloud-builders/npm'
  args: ['ci']
  dir: 'the-turkish-shop/src/api'
  id: 'install-api-deps'
  waitFor: ['-']
  ignoreFailure: true # Continue if there is no package.json

# Build React app
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: 'the-turkish-shop'
  waitFor: ['-']

# Build and push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t'
    - 'europe-west4-docker.pkg.dev/${PROJECT_ID}/firebaseapphosting-images/turkishshop'
    - '.'
  waitFor: ['install-api-deps']

# Test the image with a basic health check
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'run'
    - '--entrypoint'
    - '/app/healthcheck.sh'
    - 'europe-west4-docker.pkg.dev/${PROJECT_ID}/firebaseapphosting-images/turkishshop'

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'turkishshop'
    - '--image=europe-west4-docker.pkg.dev/${PROJECT_ID}/firebaseapphosting-images/turkishshop'
    - '--region=europe-west4'
    - '--platform=managed'
    - '--port=8080'
    - '--allow-unauthenticated'
    - '--memory=512Mi'
    - '--cpu=1'
    - '--min-instances=0'
    - '--max-instances=10'
    - '--set-env-vars=NODE_ENV=production'

images:
- 'europe-west4-docker.pkg.dev/${PROJECT_ID}/firebaseapphosting-images/turkishshop'

timeout: 1800s # 30 minutes

options:
  logging: CLOUD_LOGGING_ONLY 